/**
 * Códigos de Accion usados por la navegación y los gates de UI (espejo parcial de
 * HoyDonde.API/Authorization/Acciones.cs — única fuente de verdad real). Nunca un
 * mapa rol → acción: cada pantalla decide su visibilidad con AuthContext.hasAccion
 * contra uno de estos códigos, nunca contra un nombre de rol.
 */
export const ACCIONES = {
  USUARIO_CREAR_ADMIN: 'USUARIO_CREAR_ADMIN',
  USUARIO_CREAR_ORGANIZADOR: 'USUARIO_CREAR_ORGANIZADOR',
  CONTROL_CREAR: 'CONTROL_CREAR',
  EVENTO_CREAR: 'EVENTO_CREAR',
  EVENTO_EDITAR_PROPIO: 'EVENTO_EDITAR_PROPIO',
  EVENTO_PUBLICAR_PROPIO: 'EVENTO_PUBLICAR_PROPIO',
  EVENTO_CANCELAR_PROPIO: 'EVENTO_CANCELAR_PROPIO',
  EVENTO_VER_PROPIOS: 'EVENTO_VER_PROPIOS',
  TICKET_VER_PROPIO: 'TICKET_VER_PROPIO',
  TICKET_VALIDAR: 'TICKET_VALIDAR',
  ROL_CREAR: 'ROL_CREAR',
  ROL_EDITAR: 'ROL_EDITAR',
  ROL_ACTIVAR: 'ROL_ACTIVAR',
  ROL_ASIGNAR_ACCION: 'ROL_ASIGNAR_ACCION',
  ROL_QUITAR_ACCION: 'ROL_QUITAR_ACCION',
  ROL_ELIMINAR: 'ROL_ELIMINAR',
  USUARIO_ASIGNAR_ROL: 'USUARIO_ASIGNAR_ROL',
  USUARIO_QUITAR_ROL: 'USUARIO_QUITAR_ROL',
  USUARIO_VER_PERMISOS_EFECTIVOS: 'USUARIO_VER_PERMISOS_EFECTIVOS',
  USUARIO_DESACTIVAR: 'USUARIO_DESACTIVAR',
  REPORTE_VER_GLOBAL: 'REPORTE_VER_GLOBAL',
  REPORTE_VER_PROPIO: 'REPORTE_VER_PROPIO',
  USUARIO_RESTABLECER_PASSWORD: 'USUARIO_RESTABLECER_PASSWORD',
} as const;
